// Generated by CoffeeScript 1.6.2
(function() {
  var easing, highest_page, trans;

  easing = "easeInOutCubic";

  highest_page = 0;

  trans = function(func) {
    var active, next, off_left, off_right, previous;

    off_left = $("#content .page.off-left").add("#navigation .menu-item.off-left");
    previous = $("#content .page.previous").add("#navigation .menu-item.previous");
    active = $("#content .page.active").add("#navigation .menu-item.active");
    next = $("#content .page.next").add("#navigation .menu-item.next");
    off_right = $("#content .page.off-right").add("#navigation .menu-item.off-right");
    return func(off_left, previous, active, next, off_right);
  };

  $(document).ready(function() {
    $(".page.active").find(".page-number").show();
    $("body").on("click", ".off-left", function(event) {
      event.stopPropagation();
      if (!$(this).is(":animated")) {
        trans(function(off_left, previous, active, next, off_right) {
          active.removeClass("active").addClass("off-right");
          previous.removeClass("previous").addClass("next");
          return off_left.removeClass("off-left").addClass("active");
        });
      }
      return false;
    });
    $("body").on("click", ".previous", function(event) {
      event.stopPropagation();
      if (!$(this).is(":animated")) {
        trans(function(off_left, previous, active, next, off_right) {
          next.removeClass("next").addClass("off-right");
          active.removeClass("active").addClass("next");
          previous.removeClass("previous").addClass("active");
          return off_left.removeClass("off-left").addClass("previous");
        });
      }
      return false;
    });
    $("body").on("click", ".next", function(event) {
      event.stopPropagation();
      if (!$(this).is(":animated")) {
        trans(function(off_left, previous, active, next, off_right) {
          previous.removeClass("previous").addClass("off-left");
          active.removeClass("active").addClass("previous");
          next.removeClass("next").addClass("active");
          return off_right.removeClass("off-right").addClass("next");
        });
      }
      return false;
    });
    $("body").on("click", ".off-right", function(event) {
      event.stopPropagation();
      if (!$(this).is(":animated")) {
        trans(function(off_left, previous, active, next, off_right) {
          active.removeClass("active").addClass("off-left");
          next.removeClass("next").addClass("previous");
          return off_right.removeClass("off-right").addClass("active");
        });
      }
      return false;
    });
    return $(".carousel").owlCarousel({
      navigation: true,
      lazyLoad: true,
      navigationText: ["&larr;", "&rarr;"],
      slideSpeed: 300,
      paginationSpeed: 400,
      singleItem: true,
      autoHeight: false
    });
  });

}).call(this);
